# Generated by Django 4.1.7 on 2023-04-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('execution_date', models.DateTimeField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('performer_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='all', max_length=10)),
                ('age_from', models.IntegerField(null=True)),
                ('age_to', models.IntegerField(null=True)),
                ('height_from', models.IntegerField(null=True)),
                ('height_to', models.IntegerField(null=True)),
                ('has_international_passport', models.BooleanField(default=False)),
                ('has_tatoo_or_piercing', models.BooleanField(default=False)),
                ('other_details', models.TextField(blank=True, max_length=255, null=True)),
                ('profile_type', models.CharField(choices=[('model', 'Model'), ('photographer', 'Photographer'), ('agency', 'Agency')], default='model', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
