# Generated by Django 4.1.7 on 2023-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='posts/photos/'),
        ),
    ]
