# Generated by Django 4.2 on 2023-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_international_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_tatoo_or_piercing',
            field=models.BooleanField(default=False),
        ),
    ]
