# Generated by Django 4.1.7 on 2023-04-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
