# Generated by Django 4.1.7 on 2023-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='users/photos/'),
        ),
    ]
