# Generated by Django 4.1.7 on 2023-04-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.services.token_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('recovery_code', models.IntegerField(default=users.services.token_service.TokenService.generate_code, null=True)),
                ('expire_at', models.DateTimeField(default=users.services.token_service.TokenService.generate_expire, null=True)),
            ],
            options={
                'db_table': 'email_confirmation',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=users.services.token_service.TokenService.generate_token, max_length=100, null=True)),
                ('expire_at', models.DateTimeField(default=users.services.token_service.TokenService.generate_expire, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reset_password',
            },
        ),
    ]
